GPU_TASKS_HOME := ../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 1

COMP	   = gnu

USE_MPI    = FALSE

Bpack   := ./Make.package
Blocs   := .

include $(GPU_TASKS_HOME)/Make.Tasks
